### ISSUE TITLE
persistence example does not build

### ISSUE THREAD

**Issue by geziefer** [javaee/tutorial-examples#7] opened 2017-11-30 09:45 UTC
When running the build in the persistence example with sub-modules address-book and roster fail on build:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building address-book 8.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ address-book ---
[INFO] Deleting C:\Projects\SY\Competence Area\JavaEEExamples\tutorial-examples\persistence\address-book\target
[INFO]
[INFO] --- maven-processor-plugin:2.2.1:process (process) @ address-book ---
[INFO] Source directory: C:\Projects\SY\Competence Area\JavaEEExamples\tutorial-examples\persistence\address-book\target\generated-sources\metamodel added
[INFO] Adding compiler arg: -Aeclipselink.persistencexml=C:\Projects\SY\Competence
[INFO] Adding compiler arg: Area\JavaEEExamples\tutorial-examples\persistence\address-book/src/main/resources/META-INF/persistence.xml
[INFO] javac option: -cp
[INFO] javac option: C:\Users\alexander.ruehl\.m2\repository\org\apache\maven\maven-plugin-api\3.0.1\maven-plugin-api-3.0.1.jar [...]
[INFO] javac option: -proc:only
[INFO] javac option: -Aeclipselink.persistencexml=C:\Projects\SY\Competence
[INFO] javac option: Area\JavaEEExamples\tutorial-examples\persistence\address-book/src/main/resources/META-INF/persistence.xml
[INFO] javac option: -processor
[INFO] javac option: org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor
[INFO] javac option: -d
[INFO] javac option: C:\Projects\SY\Competence Area\JavaEEExamples\tutorial-examples\persistence\address-book\target\classes
[INFO] javac option: -s
[INFO] javac option: C:\Projects\SY\Competence Area\JavaEEExamples\tutorial-examples\persistence\address-book\target\generated-sources\metamodel
[ERROR] error on execute: invalid flag: Area\JavaEEExamples\tutorial-examples\persistence\address-book/src/main/resources/META-INF/persistence.xml

```

**Comment by ChrisWilcox78** [comment] 2018-05-14 22:41
I'm not affiliated with this project but it looks like a space in your ${basedir} path (between "Competence" and "Area") is being interpreted as the start of a new javac option.  It's likely an issue with (or expected behaviour from) the maven-processor-plugin.  They live over [here](https://github.com/bsorrentino/maven-annotation-plugin) if you want to get in touch.  

For what it's worth, I've recently run the glassfish5 version of the address-book example without any issues.

*edit: looks like someone else has had [a similar issue with the plugin](https://github.com/bsorrentino/maven-annotation-plugin/issues/62) and it may be able to be addressed by a change to the code here.  If the fix there works, I might knock up a quick PR to clean up things on this side.

**Comment by bshannon** [comment] 2018-05-14 23:08
Yes, clearly a bug in the maven-processor-plugin.  To workaround that bug, rename your directory to not include a space in the name.

**Closed as completed by bshannon** 2018-05-14 23:08 UTC
